### ISSUE TITLE
Asking

### ISSUE THREAD

**Issue by 06063004** [Villagers654/CommandSigns#2]
Do you still have faster crystal plugin?

**Comment by Villagers654** [comment]
The original plugin was a mess that didn't really help much of anything, I'm planning on a rewrite that will work more akin to [US PvP's plugin](https://cdn.discordapp.com/attachments/908091486602674307/1153490233153818684/New_USPVP_Crystal_Optimizations.mp4), and I'll open source that whenever it's done, probably in a couple of weeks.

Also, you should really be contacting me on discord @villagers654 for questions like this, lol
